//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWatcherModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaleInfoEntities : DbContext
    {
        public SaleInfoEntities()
            : base("name=SaleInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> ClientSet { get; set; }
        public DbSet<Manager> ManagerSet { get; set; }
        public DbSet<Order> OrderSet { get; set; }
        public DbSet<Product> ProductSet { get; set; }
    }
}
