//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWatcherModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string OrderDate { get; set; }
        public int Product_Id { get; set; }
        public int Client_Id { get; set; }
        public int Manager_Id { get; set; }
    
        public virtual Client ClientSet { get; set; }
        public virtual Manager ManagerSet { get; set; }
        public virtual Product ProductSet { get; set; }
    }
}
